### ISSUE TITLE
Memory overload

### ISSUE THREAD

**Issue by Konstlang** [NotWindx/Slimes-Adventure#7]
When I load my world for some reason it drains all my memory(mb my pc specs are too low) here are logs: https://mclo.gs/wsdagRc
And here are my specs:

Processor	Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz   3.10 GHz
Installed RAM	8.00 GB
System type	64-bit operating system, x64-based processor

**Comment by Konstlang** [comment]
Ok I solved my problem. It was RAM limit on the launcher. I have increased i and it now works just fine.

**Comment by NotWindx** [comment]
i'm glad it was just the memory i try my best to keep the specs low, so that everyone is able to enjopy
